# Generated by Django 3.2.8 on 2021-10-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок альбома')),
                ('description', models.TextField(blank=True, max_length=254, verbose_name='Описание альбома')),
                ('photo', models.ImageField(upload_to='album_presentation', verbose_name='Фотография')),
                ('is_publish', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Альбом создан')),
                ('slug', models.SlugField(max_length=55, unique=True, verbose_name='URL альбома')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoInHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок фотографии')),
                ('description', models.TextField(blank=True, max_length=254, verbose_name='Описание для фотографии')),
                ('photo', models.ImageField(upload_to='photo_home', verbose_name='Фотография')),
                ('text_on_left', models.BooleanField(default=True, verbose_name='Текст слева')),
            ],
            options={
                'verbose_name': 'Фотография на home',
                'verbose_name_plural': 'Фотографии на home',
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo_albums/%Y/%m/%d/', verbose_name='Фотография альбома')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотография альбома',
                'verbose_name_plural': 'Фотографии альбома',
            },
        ),
    ]
